name: "Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:

  dotnet-job:
    name: "Build .NET solution"
    needs: [native-job]
    runs-on: ubuntu-latest
    steps:

      - name: "Clone Git repository"
        uses: actions/checkout@v3

      - name: ".NET Build"
        run: dotnet build "./src/cs" --nologo --verbosity minimal --configuration Release -p:Version="$(date +'%Y.%m.%d')"
          
